CREATE TABLE IF NOT EXISTS stock (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    amount NUMERIC(12, 4) NOT NULL,
    PRIMARY KEY(id),

    CONSTRAINT fk_stock_product
        FOREIGN KEY (product_id) REFERENCES products(id),

    CONSTRAINT fk_stock_position
        FOREIGN KEY (position_id) REFERENCES positions(id),

    CONSTRAINT uk_stock_product_position
        UNIQUE (product_id, position_id)
);

CREATE TABLE IF NOT EXISTS movement (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_code VARCHAR(50) NOT NULL,
    from_position VARCHAR(50),
    to_position VARCHAR(50),
    requested_by VARCHAR(50),
    amount NUMERIC(12, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    movement_type VARCHAR(25) NOT NULL,
    responsible VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);