CREATE TABLE IF NOT EXISTS stock (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    amount NUMERIC(12, 4) NOT NULL,
    PRIMARY KEY(id),

    CONSTRAINT fk_stock_product
        FOREIGN KEY (product_id) REFERENCES products(id),

    CONSTRAINT fk_stock_position
        FOREIGN KEY (position_id) REFERENCES positions(id),

    CONSTRAINT uk_stock_product_position
        UNIQUE (product_id, position_id)
);