CREATE TABLE IF NOT EXISTS picking_order (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    separator_id BIGINT,
    assigned_at TIMESTAMP,
    finished_at TIMESTAMP,
    canceled_at TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    PRIMARY KEY(id),

    CONSTRAINT fk_picking_order_users
            FOREIGN KEY (separator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS picking_products (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    requested_amount NUMERIC(12, 4) NOT NULL,
    collected_amount NUMERIC(12, 4) NOT NULL DEFAULT 0,
    suggested_position VARCHAR(20) NOT NULL,
    product_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    status_collected VARCHAR(20) NOT NULL,
    PRIMARY KEY(id),

    CONSTRAINT fk_picking_products_products
        FOREIGN KEY (product_id) REFERENCES products (id),

    CONSTRAINT fk_picking_products_order
            FOREIGN KEY (order_id) REFERENCES picking_order (id)
);